gradxchange/gradxchange/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    #home page
    path('', user_views.home, name='home'),
    #admin site
    path('admin/', admin.site.urls),
    
    #item / service
    path('item/', include('item.urls')),
    path('service/', include('service.urls')),
   
    #authentication
    path('signup/',user_views.signup, name='signup'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
        
    #profiles
    path('account/<str:username>/',user_views.accountPage, name='account'),
    #edit profile
    path('edit/',user_views.edit, name='edit'),
    #edit about me
    path('edit_about/',user_views.edit_about, name='edit_about'),
    
    #whatsapp 
    path('redirect_to_whatsapp/<str:whatsapp_number>/', user_views.redirectToWhatsApp, name='redirect_to_whatsapp'),

  
    #password change
    path('password_change/',authentication_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_change/done',authentication_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    #password reset
    #submit email form
    path('password_reset/', authentication_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'),name="password_reset"),
    #Email sent success message
    path('password_reset/done', authentication_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name="password_reset_done"),
    #Link to password rest form in email
    path('reset/<uidb64>/<token>', authentication_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    #Password successfully changed message
    path('reset/done/',authentication_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),

    #messages
    path('inbox/', user_views.inbox, name='inbox'),
    path('chat/<int:profile_id>/', user_views.chat, name='chat'),

   
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gradxchange/item/urls.py
from . import views
from django.urls import path

app_name='item'
urlpatterns = [
 
    
    path('', views.index, name='index'),
    #detail
    path('<int:pk>/', views.detail, name='detail'),
    #add item
    path('add', views.create_item, name='create_item'),
    #edit item
    path('edit/<int:id>/', views.update_item,name='update_item'),
    #delete item
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
    
    #like
    path('like',views.like_item, name='like'),
    
    path('change_status/<int:item_id>/<str:new_status>/', views.change_status, name='change_status'),
    
    path('item/relist/<int:pk>/', views.relist_item, name='relist_item'),

    
       # #/item/ 
    # path('', views.IndexClassView.as_view(), name='index'),
    # #/item/1
    # path('<int:pk>/', views.ItemDetail.as_view(), name='detail'),
    # #add item
    # path('add/', views.CreateItem.as_view(), name='create_item'),

]

gradxchange/service/urls.py
from . import views
from django.urls import path

app_name='service'
urlpatterns = [
    path('', views.index, name='index'),
    #detail
    path('<int:pk>/', views.detail, name='detail'),
    #add service
    path('add', views.create_service, name='create_service'),
    #edit service
    path('edit/<int:id>/', views.update_service,name='update_service'),
    #delete service
    path('delete/<int:id>/', views.delete_service,name='delete_service'),
    
    path('like',views.like_service, name='like_service'),
    
    path('change_status/<int:service_id>/<str:new_status>/', views.change_status, name='change_status'),

    path('service/relist/<int:pk>/', views.relist_service, name='relist_service'),


]

gradxchange/item/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.core.validators import MinValueValidator, RegexValidator
from decimal import Decimal

class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    
    tags = TaggableManager()
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_detail = models.CharField(max_length=2000)
    item_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    item_image = models.ImageField(upload_to='images_item', default="notfound.png")
    created =  models.DateTimeField(auto_now_add=True)
    #user's item
    user_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,default=1)
    
    #people that liked the item
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='item_liked',blank= True)
    
    #item status
    class Status(models.TextChoices):
        AVAILABLE = 'AV', 'Available'
        SOLD = 'SO', 'Sold'

    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.AVAILABLE,)
   
    #item's detail view for new created item
    def get_absolute_url(self):
       return reverse("item:detail", kwargs={"pk": self.pk})

class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='comment')
    body = models.TextField() #short comments no paragraph
    created = models.DateTimeField(auto_now=True)
    commented_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='item_comments')
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return self.body

gradxchange/item/forms.py
from django import forms
from .models import Item, Comment
from taggit.forms import TagField
from django.core.exceptions import ValidationError


class ItemForm(forms.ModelForm):
    tags = TagField(required=False, help_text="Enter comma-separated tags")


    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_detail','item_price','item_image','tags']
        widgets = {
            'item_name': forms.TextInput(attrs={'class': 'form-control'}),
            'item_desc': forms.TextInput(attrs={'class': 'form-control'}),
            'item_detail': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'item_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'item_image': forms.FileInput(attrs={'class': 'form-control'}),
        }
        
        def clean_item_price(self):
            item_price = self.cleaned_data['item_price']
            if item_price < 0:
                 raise ValidationError('Price cannot be negative.')
            return item_price
    
        labels = {
            'item_name': "Item's Name",
            'item_desc': "Item's Description",
            'item_detail': "Item's Details",
            'item_price': "Item's Price",
            'item_image': "Item's Image",
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body',]
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
       

gradxchange/item/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.decorators import login_required
# #class based view
# from django.views.generic.list import ListView
# from django.views.generic.detail import DetailView
# from django.views.generic.edit import CreateView

from django.urls import reverse

from .models import Item
from .forms import ItemForm
from .forms import CommentForm

from django.core.paginator import Paginator
from django.utils.dateparse import parse_date

from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.http import JsonResponse
from django.db.models import Count
from django.utils import timezone


def index(request):
    item_list = Item.objects.select_related('user_name').filter(status=Item.Status.AVAILABLE).annotate(like_count=Count('liked_by')).all().order_by('-created')  # Include related user data

    # Retrieve the tag from the URL parameter
    tag = request.GET.get('tag')
    if tag:
        item_list = item_list.filter(tags__name__in=[tag])

    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    show_my_items = request.GET.get('show_my_items', 'off')

    search_type = request.GET.get('search_type')
    search_query = request.GET.get('search_query')

    # To store the active filter name and value for displaying in the template
    active_filter_name = None
    active_filter_value = None

    if search_type == 'item_name' and search_query:
        item_list = item_list.filter(item_name__icontains=search_query)
        active_filter_name = 'Item Name'
        active_filter_value = search_query
    
    elif search_type == 'seller_name' and search_query:
        item_list = item_list.filter(user_name__username__icontains=search_query)
        active_filter_name = 'Seller Name'
        active_filter_value = search_query

     # Adjust price filter to allow independent min and max 
    if min_price:
        item_list = item_list.filter(item_price__gte=min_price)
        active_filter_name = 'Minimum Price'
        active_filter_value = f"RM {min_price}+"
    if max_price:
        item_list = item_list.filter(item_price__lte=max_price)
        active_filter_name = 'Maximum Price'
        active_filter_value = f"Up to RM {max_price}"

    if start_date:
        start_date = datetime.strptime(start_date, '%Y-%m-%d')
        start_date = timezone.make_aware(start_date, timezone.get_default_timezone())
        item_list = item_list.filter(created__gte=start_date)

    if end_date:
        end_date = datetime.strptime(end_date, '%Y-%m-%d')
        end_date = timezone.make_aware(end_date, timezone.get_default_timezone())
        end_date = end_date + timedelta(days=1) - timedelta(seconds=1)
        item_list = item_list.filter(created__lt=end_date)  # Using __lt to include "just before midnight"

    if show_my_items == 'on':
        item_list = item_list.filter(user_name=request.user)
        active_filter_name = 'My Items'
        active_filter_value = 'My items'
    

   # Ensure pagination works with the current filters
    page_number = request.GET.get('page')
    paginator = Paginator(item_list, 12)  # Assuming 12 items per page
    page_obj = paginator.get_page(page_number)

    context = {
        'item_list': page_obj,
        'result_count': page_obj.paginator.count,
        'show_my_items': show_my_items,
        'active_filter_name': active_filter_name,
        'active_filter_value': active_filter_value,
        'tag': tag,  # Optionally pass the tag to highlight it or use it in the template
        'start_date': start_date,  # Pass start_date to the template
        'end_date': end_date,  # Pass end_date to the template
        'min_price': min_price,  # Pass min_price to the template
        'max_price': max_price,  # Pass max_price to the template
    }
    return render(request, 'item/index.html', context)

def update_breadcrumb(request, name, url):
    # Get the current breadcrumb list from session, or initialize it if it doesn't exist
    breadcrumb = request.session.get('breadcrumb', [])
    
    # Check if the current URL already exists in the breadcrumb trail
    if breadcrumb and breadcrumb[-1]['url'] == url:
        # Avoid duplicating the last entry if the page was refreshed
        pass
    else:
        # Check for existing entries and remove the oldest if length is already 5
        breadcrumb.append({'name': name, 'url': url})
        if len(breadcrumb) > 5:
            breadcrumb = breadcrumb[-5:]  # Keep only the last 5 elements
    
    # Update the session
    request.session['breadcrumb'] = breadcrumb
    
def detail(request,pk):
    item = get_object_or_404(Item, pk=pk)
    
    update_breadcrumb(request, item.item_name, request.path)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.item = item
            new_comment.commented_by = request.user  # Ensure this is an authenticated user
            new_comment.save()
            messages.success(request, 'Your comment was added successfully!')

            return redirect(item.get_absolute_url())  # Redirect to the same page to show the new comment
        else:
            # If the form is not valid
            print(comment_form.errors)
    else:
        comment_form = CommentForm()
        
    user_has_liked = False
    if request.user.is_authenticated:
        user_has_liked = item.liked_by.filter(id=request.user.id).exists()
        
    profile_id = item.user_name.profile.pk  # This gets the profile ID of the item owner to send a message
    
    # Find related items based on tags
    related_items = Item.objects.filter(tags__name__in=item.tags.names()).exclude(id=item.id).distinct()
    
    context = {
        'item':item,
        'comment_form': comment_form ,
        'profile_id': profile_id, 
        'related_items': related_items,
        'user_has_liked': user_has_liked,
    }
    return render(request, 'item/detail.html', context)

#liked by users
@login_required
def like_item(request):
    if request.method == 'POST':
        item_id = request.POST.get('item_id')
        item = get_object_or_404(Item, id=item_id)
        
        if item.liked_by.filter(id=request.user.id).exists():
            item.liked_by.remove(request.user)
            liked = False
        else:
            item.liked_by.add(request.user)
            liked = True
        
        return JsonResponse({
            'liked': liked,
            'total_likes': item.liked_by.count()
        })
    else:
        return HttpResponse(status=405)  # Method not allowed
 

@login_required
def create_item(request):
    form = ItemForm()  # Create an instance of the form for GET requests
    
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)  # Re-create instance for POST
        
        if form.is_valid():
            new_item = form.save(commit=False)  # Save the form temporarily without committing to the database
            new_item.user_name = request.user  # Set the user_name field to the currently logged in user
            new_item.save()  # Now save the item to the database
            form.save_m2m()  # Save the many-to-many data for the form, including tags
            messages.success(request, 'Item created successfully!')
             # Redirect the user back to their account page
            return redirect(reverse('account', kwargs={'username': request.user.username}))

        else:
            context = {'form': form}
            return render(request, 'item/item-form.html', context)

    # This will now always be defined for GET requests
    return render(request, 'item/item-form.html', {'form': form})

@login_required
def update_item(request, id):
    # Use get_object_or_404 to handle cases where the item doesn't exist
    item = get_object_or_404(Item, id=id)

    # Check if the request is POST to handle form submission
    if request.method == 'POST':
        # Initialize the form with POST data and files, using the item instance
        form = ItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Item updated successfully!')  # Add success message

            # Instead of redirecting, re-render the page with the form
            # This keeps the user on the current page and shows the success message
            return render(request, 'item/item-form.html', {'form': form, 'item': item})
    else:
        # If not POST, initialize the form with the item instance for editing
        form = ItemForm(instance=item)
    
    # Render the page with the form for both GET requests and invalid form submissions
    return render(request, 'item/item-form.html', {'form': form, 'item': item})

@login_required
def delete_item(request,id):
    item = Item.objects.get(id=id)
    
    if request.method =='POST':
        item.delete()
        messages.success(request, 'Item deleted successfully!')
        return redirect(reverse('account', kwargs={'username': request.user.username}))

    
    return render (request, 'item/item-delete.html', {'item':item})

def change_status(request, item_id, new_status):
    item = get_object_or_404(Item, id=item_id)
    if request.user == item.user_name:
        item.status = new_status
        item.save()
    else:
        messages.error(request, 'You are not authorized to change the status of this item.')
    # return redirect('item:detail', pk=item.pk)
    return redirect(reverse('account', kwargs={'username': request.user.username}))

def relist_item(request, pk):

gradxchange/item/templates/item/index.html
{% extends 'users/base.html' %}
{% load static %}
{% load item_custom_filters %}
{% block body %}

<style>
    #searchFormContainer {
        width: 100%;
        display: flex;
        justify-content: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    #searchForm {
        max-width: 900px;
        width: 100%;
        padding: 15px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        display: flex;
        /* Ensures form elements are flex items */
        align-items: center;
    }

    .search-input-group {
        display: flex;
        flex-wrap: wrap;
        /* Allows wrapping if necessary */
        gap: 10px;
        /* Space between form elements */
        width: 100%;
        /* Ensures the group takes full width of the form */
    }

    .custom-select,
    .form-control {
        flex: 1 0 auto;
        /* Allows these elements to grow and shrink */
    }

    .search-btn,
    .view-all-btn {
        flex: 0 1 auto;
        /* Prevents these buttons from growing too large */
    }


    /* Styles for Cards and Images */
    .zoom-card:hover,
    .zoom-image:hover {
        transform: scale(1.05);
    }

    .filter-column,
    .ads-column {
        padding: 20px;
        background-color: white;
    }

    .item-card-body {
        padding: 10px;
        display: flex;
        flex-direction: column;
    }

    @media (min-width: 768px) {
        .search-input-group .col-md-3 {
            display: flex;
            gap: 5px;
            /* Adds space between buttons */
            align-items: center;
            /* Aligns items vertically in the middle */
        }

        .search-btn,
        .view-all-btn {
            flex: 1;
            /* Each button takes equal space */
        }
    }

    @media (max-width: 767px) {
        .search-input-group {
            flex-direction: row;
            /* Aligns children in a row */
        }

        .search-btn,
        .view-all-btn {
            flex: 1;
            /* Allows buttons to fill the space equally */
        }
    }
</style>

<div class="container-fluid">
    <div class="row">
        <!-- Filters Column Toggle Button -->
        <div class="col-12 d-md-none">
            <button class="btn btn-primary w-100 mb-2" type="button" data-toggle="collapse" data-target="#filterMenu"
                aria-expanded="false" aria-controls="filterMenu">
                <i class="fas fa-filter"></i> <!-- Font Awesome Filter Icon -->
            </button>
        </div>

        <!-- Filters Section -->
        <section class="col-md-2 filter-column collapse d-md-block" id="filterMenu">
            <h5>Filters</h5>
            <form action="" method="get" class="d-grid gap-2">
                <!-- Date Filters -->
                <label for="start_date">Start Date:</label>
                <input type="date" id="start_date" name="start_date" class="form-control mb-2" placeholder="yyyy-mm-dd">
                {% if start_date %}
                <small>Current filter: {{ start_date|date:"F j, Y" }}</small>
                {% endif %}

                <label for="end_date">End Date:</label>
                <input type="date" id="end_date" name="end_date" class="form-control mb-2" placeholder="yyyy-mm-dd">
                {% if end_date %}
                <small>Current filter: {{ end_date|date:"F j, Y" }}</small>
                {% endif %}

                <!-- Price Filters -->
                <label for="min_price">Minimum Price:</label>
                <input type="number" id="min_price" name="min_price" class="form-control mb-2"
                    placeholder="Minimum Price">
                {% if min_price %}
                <small>Current filter: Min RM {{ min_price|floatformat:"2" }}</small>
                {% endif %}
                <label for="max_price">Maximum Price:</label>
                <input type="number" id="max_price" name="max_price" class="form-control mb-2"
                    placeholder="Maximum Price">
                {% if max_price %}
                <small>Current filter: Max RM {{ max_price|floatformat:"2" }}</small>
                {% endif %}

                <!-- Checkbox for showing user's items -->
                {% if user.is_authenticated %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="on" name="show_my_items" id="showMyItems"
                        {%if request.GET.show_my_items == 'on' %}checked{% endif %}>
                    <label class="form-check-label" for="showMyItems">Show My Items Only</label>
                </div>
                {% endif %}
                <!-- Submit Button -->
                <button class="btn btn-primary mt-3" type="submit">Apply Filters</button>
            </form>
        </section>


        <!-- Main Content Column -->
        <section class="col-12 col-md-8">
            <div class="alert alert-info" role="alert" {% if not show_my_items == 'on' %}style="display:none;" {%endif%}>
                Showing only your items.
            </div>

            <!-- New search form container -->
            <div id="searchFormContainer">
                <div id="searchForm">
                    <form action="" method="GET" class="input-group search-input-group">
                        <div class="row no-gutters align-items-center justify-content-center">
                            <div class="col-12 col-md-5">
                                <select class="form-control custom-select" name="search_type">
                                    <option value="item_name">Search by Item's Name</option>
                                    <option value="seller_name">Search by Seller's Name</option>
                                </select>
                            </div>
                            <div class="col-12 col-md-4">
                                <input class="form-control" type="search" name="search_query"
                                    placeholder="Enter search term" aria-label="Search">
                            </div>
                            <div class="col-12 col-md-2">
                                <button class="btn btn-primary search-btn" type="submit"><i class="fas fa-search"></i>
                                    Search</button>
                            </div>
                            <div class="col-12 col-md-1">
                                <a href="{% url 'item:index' %}" class="btn btn-secondary view-all-btn"><i
                                        class="fas fa-list"></i> View All</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="text-center mb-4">
                <hr>
                <div class="text-center mb-4" style="padding-top: 5px;">

                    {% if min_price and max_price %}
                    <h5>Showing results for "Price range: RM {{ min_price|floatformat:"2" }} to RM {{
                        max_price|floatformat:"2" }}": {{ result_count }}</h5>
                    {% elif active_filter_name == 'Seller Name' %}
                    <h5>Showing results for {{ active_filter_name }} "{{ active_filter_value }}": {{ result_count }}
                    </h5>
                    {% elif active_filter_name %}
                    <h5>Showing results for "{{ active_filter_value }}": {{ result_count }}</h5>
                    {% elif start_date and end_date %}
                    <h5>Showing results from "{{ start_date|date:"F j, Y" }}" to "{{ end_date|date:"F j, Y" }}": {{
                        result_count }}</h5>
                    {% else %}
                    <h5>Total items: {{ result_count }}</h5>
                    {% endif %}
                    {% if tag %}
                    <h4>Showing results for tag: "{{ tag }}"</h4>
                    {% endif %}


                </div>
            </div>
            <div id="item-cards-section" style="background-color: #f8f8ff;padding-top: 10px;">
                <div class="container py-2">

                    {% for item in item_list %}
                    <div class="card mb-4 zoom-card">
                        <div class="row align-items-center">
                            <div class="col-md-3">
                                <div class="bg-image zoom-image ripple" style="overflow: hidden;">
                                    <a href="{% url 'item:detail' item.id %}" class="text-reset">
                                        <img src="{{ item.item_image.url }}" class="img-fluid"
                                            style="width: 100%; height: 150px; object-fit: contain;">
                                    </a>
                                </div>
                            </div>

                            <div class="col-md-9">
                                <div class="card-body item-card-body">
                                    <a href="{% url 'item:detail' item.id %}" class="text-reset">
                                        <h5 class="card-title mb-1">{{ item.item_name }}</h5>
                                        <p class="mb-1 text-muted">{{ item.item_desc }}</p>
                                        <h5 class="mb-2 text-danger">RM {{ item.item_price }}</h5>
                                        <p class="small mb-2">{{ item.like_count }} Likes</p>
                                    </a>
                                    <div>
                                        <div class="tags">
                                            <p>Tags:
                                                {% if item.tags.all %}
                                                {% for tag in item.tags.all %}
                                                <a href="{% url 'item:index' %}?tag={{ tag.name }}"><span
                                                        class="tag">{{tag.name }}</span></a>
                                                {% endfor %}
                                                {% else %}
                                                <small>No Tags</small>
                                                {% endif %}
                                            </p>
                                        </div>
                                        {% if request.user != item.user_name %}
                                        <a id="send-message-btn" href="{% url 'chat' item.user_name.profile.pk %}"
                                            class="btn btn-info">Chat Now</a>
                                        {% else %}
                                        <a href="{% url 'item:update_item' item.id %}"
                                            class="btn btn-outline-warning btn-sm">Edit</a>
                                        <a href="{% url 'item:delete_item' item.id %}"
                                            class="btn btn-outline-danger btn-sm">Delete</a>
                                        <a href="{% url 'item:change_status' item.id 'SO' %}"
                                            class="btn btn-info btn-sm">Mark as Sold</a>
                                        {% endif %}




                                    </div>
                                    <p class="small">Listed by <a
                                            href="{% url 'account' item.user_name.username %}">@{{item.user_name}}</a>
                                        on {{ item.created|date:"F d, Y" }}</p>
                                </div>
                            </div>

                        </div>
                    </div>
                    {% empty %}
                    <div class="col-12">
                        <p class="text-center">No items found.</p>
                    </div>
                    {% endfor %}
                </div>
                <!-- Debugging output <div>Debug URL Params: {{ request.GET.urlencode }}</div>-->


            </div>
            <!-- Pagination -->
            <div class="container" style="max-width: 900px; background-color: white;">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="pagination justify-content-center" style="align-items:center; display:flex;">
                            {% if item_list.has_previous %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="?{{ request.GET|remove_param:'page' }}&page={{ item_list.previous_page_number }}">Previous</a>
                            </li>
                            {% endif %}
                            <li class="page-item" style="margin: 0 10px; text-align: center;">
                                Page: {{ item_list.number }} of {{ item_list.paginator.num_pages }}
                            </li>
                            {% if item_list.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="?{{ request.GET|remove_param:'page' }}&page={{ item_list.next_page_number }}">Next</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}